on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello to dev, when commits are done
    steps:
    - name: Hello world action step
      id: hello
      uses: VaibhavAvasarala/GithubAction@master
      with:
        who-to-greet: 'Vaibhav Avasarala'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
